apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - image: gcr.io/fit-guide-296101/github.com/thaimac/comp4312finalproject
          imagePullPolicy: IfNotPresent
          name: app-sha256-1
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: app
  name: app-hpa-yosr
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app
---
apiVersion: v1
kind: Service
metadata:
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: app
  name: app-service
  namespace: default
spec:
  clusterIP: 10.4.13.109
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 30285
      port: 443
      protocol: TCP
      targetPort: 8000
  selector:
    app: app
  sessionAffinity: None
  type: LoadBalancer

